feat: 예약 취소 기능 구현
Upjuyanolja/Upjuyanolja_BE pull request #102
Opened 2024-01-16 11:53 UTC by chaewon12

### 💡Motivation
- 예약 취소 기능 구현

### 📌Changes
- 객실, 쿠폰 재고 증가 로직
- 쿠폰 사용 내역 제거 로직 

### 🫱🏻‍🫲🏻To Reviewers

2024-01-16 16:25 UTC, JeongUijeong requested changes
구글 컨벤션 적용하신 후 tab, indent 모두 4로 맞춰주세요!
![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/94631526/2e4712cb-790e-4e37-8de5-56730f16287a)

2024-01-16 19:47 UTC, matrixpower1004 approved these changes
수고하셨습니다. 👍

2024-01-17 01:36 UTC, JeongUijeong approved these changes
수고하셨습니다! 🧡

2024-01-17 01:36 UTC, chaewon12 commented
> 구글 컨벤션 적용하신 후 tab, indent 모두 4로 맞춰주세요! ![image](https://private-user-images.githubusercontent.com/94631526/297121458-2e4712cb-790e-4e37-8de5-56730f16287a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTUzMjcsIm5iZiI6MTcwNTQ1NTAyNywicGF0aCI6Ii85NDYzMTUyNi8yOTcxMjE0NTgtMmU0NzEyY2ItNzkwZS00ZTM3LThkZTUtNTY3MzBmMTYyODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxMzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNjlmMzllMDBmMTIyZDA5YWQzMjA2Y2IzNWI4ZTEwYjU1YWE2MGU0NzhiNmEyOTM4OWU1M2ViMzFhNGE1N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cdyjQtD_LAgUOoqJYnazevu9zURdffKFbuo3IwSTJec)

에고... 구글 컨벤션 적용을 해놨는데 기본이 tab = 2 더라고요 
따로 말씀 없으시길래 2로 하시는 줄 알았습니다 ㅠㅜ

제 intellij 설정이 저장 시 자동 포맷팅이라 이 PR 말고도 이전 작업에서도 다른 파일들 tab이 자동 변경됐어서 
이 PR까지 머지 후 Refactor 이슈 파서 올려도 될까요?

2024-01-17 01:39 UTC, merged