#109 feat: 쿠폰 관리 화면 View API 구현 완료
Upjuyanolja/Upjuyanolja_BE pull request #133
Opened 2024-01-21 02:39 UTC by matrixpower1004

### 💡Motivation
- 쿠폰 관리 화면 View API 구현

### 📌Changes
- 쿠폰 관리 화면 응답 API 구현
- 쿠폰 관리 화면 응답 Test 작성
- 쿠폰 관리 화면 응답 REST Docs 작성

### 🫱🏻‍🫲🏻To Reviewers
- 하고 싶은 말이 있다면 적어주세요.

2024-01-21 10:13 UTC, JeongUijeong requested changes
수고하셨습니다! 😊👍🏻

2024-01-21 10:13 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
> +                .message("쿠폰 조회에 성공하였습니다.")
responseRoomsView의 응답 message와 같은데 의도하신 건가요??

2024-01-21 10:13 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageQueryDto.java
> +    Long accommodationId,
공백 제거 부탁 드려요~~
```suggestion
public record CouponManageQueryDto(
    Long accommodationId,
```

2024-01-21 10:13 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponInfo.java
> +    Long couponId,
공백 제거 부탁 드려요!
```suggestion
public record CouponInfo(
    Long couponId,
```

2024-01-21 10:13 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageRooms.java
> +) {
공백 제거 부탁 드려용
```suggestion
    List<CouponInfo> coupons
) {
```

2024-01-21 14:50 UTC, chaewon12 approved these changes
수고하셨습니다 👍

2024-01-22 01:13 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
> +                .message("쿠폰 조회에 성공하였습니다.")
네. 객실별로 쿠폰 현황만 내려주는 것이라 조회라고 생각해서 메시지를 통일했습니다.

2024-01-22 01:17 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageQueryDto.java
> +    Long accommodationId,
네. 수정해서 다시 올렸습니다.

2024-01-22 01:17 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponInfo.java
> +    Long couponId,
수정해서 다시 올렸습니다.

2024-01-22 01:18 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/dto/response/backoffice/CouponManageRooms.java
> +) {
수정해서 다시 올렸습니다.

2024-01-23 04:13 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/controller/CouponBackofficeController.java
> +                .message("쿠폰 조회에 성공하였습니다.")
넵

2024-01-23 04:14 UTC, JeongUijeong approved these changes
수고하셨습니다!! 👍🏻

2024-01-23 05:26 UTC, merged