feat : 회원가입 기능 구현
Upjuyanolja/Upjuyanolja_BE pull request #22
Opened 2023-12-28 12:49 UTC by chadongmin

### 💡Motivation
- 회원가입 기능을 구현했습니다.
### 📌Changes
- 전화번호 길이가 - 문자를 포함하면 13자리라서 Member 엔티티의 phone의 속성을 length 12에서 13으로 수정했습니다.

### 🫱🏻‍🫲🏻To Reviewers
- Exception에 대한 응답처리는 아직 하지 않았습니다.

2023-12-28 13:37 UTC, JeongUijeong requested changes
수고 많으셨습니다 😊👍🏻 시큐리티 부분은 추후 개발되는 걸로 이해하고 감안하여 코드 리뷰를 남겼습니다! ㅎㅎ
전체적으로 공백이나 컨벤션에서 정한 부분에서 조금 세세하게 적어드렸는데, 번거로우시겠지만 수정 부탁 드립니다..🥹 
수정 후 알려주시면 approve 해드리도록 하겠습니다.

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
> +    }
data를 비워서 응답하고 싶으시다면, ResponseEntity<SuccessResponse<Void>> 로 작성하시면 됩니다! 
그리고 별 건 아니지만 꺽쇠 와 vertifyEmail 사이에 공백이 없습니다! 추가해주세요~~😊

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
> +@RequestMapping("/members")
"/api/members" 로 수정 부탁드립니다~! ㅎㅎ

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/SingUpRequest.java
> +    @Nullable
이 사이에는 공백이 없네요! 추가해주시면 더 일관성 있을 것 같습니다 ㅎㅎ

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/SignUpResponse.java
> +@Builder
컨벤션에 맞게 @Getter와 @NoArgsConstructor(access = AccessLevel.PROTECTED) 만 사용해주시고, @AllArgsConstruct는 삭제, @Builder는 생성자를 만들어서 해당 생성자에 붙여주세요! 😊

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Member.java
현아님이 가독성을 위해 엔터티 필드 간 공백을 넣자고 제안 주셨습니다! 맞춰주실 수 있을까요~? 🥹

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberEmailDuplicationException.java
> +    }
Override가 필요한 이유가 있을까요?

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/repository/MemberRepository.java
> +    Optional<Member> findByEmail(String email);
사이에 한 줄 띄워주셔야 합니다 (구글 컨벤션) ! ㅎㅎ

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
> +public class MemberRegisterService {
서비스 클래스를 기능마다 분리하시나요~? 혹시 이유가 있으실까요?

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
> +
공백 없애 주시면 감사하겠습니다! ㅎㅎ

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberEmailDuplicationException.java
> +        super(errorCode);
해당 예외의 경우 ErrorCode가 정해져 있기 때문에 서비스 로직에서 입력하도록 받기보다 매개변수 없이 
```
    public MemberEmailDuplicationException() {
        super(ErrorCode.DUPLICATED_EMAIL);
    }
```
이렇게 구현하시면 서비스 로직에서 불필요한 코드가 사라질 것 같습니다!

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/global/security/SecurityConfig.java
> +
공백 삭제 부탁드립니다!

2023-12-28 13:37 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/global/security/SecurityConfig.java
> +    @Bean
사이에 공백 추가해주세요!

2023-12-28 13:55 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
> +    }
수정완료했습니다!

2023-12-28 13:55 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/controller/MemberController.java
> +@RequestMapping("/members")
수정완료했습니다!

2023-12-28 13:55 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/request/SingUpRequest.java
> +    @Nullable
수정완료했습니다!

2023-12-28 13:55 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/SignUpResponse.java
> +@Builder
수정완료했습니다!

2023-12-28 13:55 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/entity/Member.java
수정완료했습니다!

2023-12-28 13:56 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
> +public class MemberRegisterService {
이 부분은 좀 더 고민후에 말씀드리도록 하겠습니다. 다른 분들 코드를 참고해서 하다보니 분리를 해놨는데 추후에 수정될 수도 있을 것 같아요

2023-12-28 13:57 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
> +
수정완료했습니다!

2023-12-28 13:57 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberEmailDuplicationException.java
> +        super(errorCode);
수정완료했습니다!

2023-12-28 14:09 UTC, decten commented
팀장님이 거의 인간 체크 스타일인데요ㅋㅋ  컨벤션 검사를 CI에 넣어서 자동으로 진행할 걸 그랬습니다

2023-12-28 14:09 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberRegisterService.java
> +public class MemberRegisterService {
넵! 알겠습니당

2023-12-28 14:12 UTC, JeongUijeong approved these changes

2023-12-29 02:14 UTC, decten approved these changes

2023-12-29 02:17 UTC, merged