refactor: erd 변경과 코드 수정
Upjuyanolja/Upjuyanolja_BE pull request #227
Opened 2024-02-03 19:00 UTC by decten

### 💡Motivation
- 개발 피드백을 바탕으로 db erd를 수정하고, 코드를 변경했습니다
https://www.erdcloud.com/d/fpNBFtPodeq6TPi76

### 📌Changes
- address 테이블 삭제 및 accommodation에 병합
- accommodation & room 모두 option의 외래 키 관계 변경
- roomStock 양방향 삭제
- accommodation & room 모두 image 양방향 삭제
- room에서 roomPrice와 외래 키 관계 변경

### 🫱🏻‍🫲🏻To Reviewers
- 테스트 코드는 모두 통과 했고 채원님이랑 지상님 서비스 코드는 거의 변동이 없지만, api가 원래처럼 잘 동작하는지 다들 확인 부탁 드립니다
- 특히 팀장님 부분이 많이 변경 됐는데, 오픈 api와 이미지 로직이 괜찮은지 확인 부탁 드립니다
- 지금 pr 보시다시피 하나 건드리면 다른 도메인 비즈니스 코드 & 테스트 코드 & sql 작성에 모두 영향이 가기 때문에, 수정 사항이 있다면 해당 브랜치로 커밋을 보내주시고 지금 pr로 한 번에 develop에 보내려고 합니다
- **해당 pr은 모든 분들이 괜찮으시고, sql 백업까지 제가 다 준비 하면 카톡으로 한 번 더 말씀 드리고 제가 머지하겠습니다**

2024-02-04 09:37 UTC, decten commented
레디스 주석 처리도 같이 올라갔네요 수정해서 다시 커밋 하겠습니다

2024-02-05 12:46 UTC, JeongUijeong requested changes
수고하셨습니다!! 제가 수정할 부분 수정한 후 approve 하도록 하겠습니다! 😊

2024-02-05 12:46 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/dto/request/AccommodationOptionRequest.java
> +    Long AccommodationId,
API 명세가 달라집니다! 제가 수정해서 본 PR에 커밋 올리겠습니다!

2024-02-05 12:46 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/global/exception/ErrorCode.java
> +    ROOM_PRICE_NOT_FOUND(HttpStatus.NOT_FOUND, 3002, "객실 가격 정보를 찾을 수 없습니다."),
새로 Error Code가 추가되는 경우 다음 숫자로 넣어야 합니다! 지금처럼 되면 기존에 작성한 문서들에서 에러코드 관련 내용을 모두 수정해야 합니다..!🥲 제가 본 PR에서 다시 수정해서 커밋하겠습니다~

2024-02-05 15:48 UTC, JeongUijeong approved these changes
필요한 내용 수정 완료했습니다~😊

2024-02-06 10:53 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
> +            roomQueryUseCase.findRoomPriceByRoom(room).getOffWeekDaysMinFee(), coupon);
이전에는 roomPrice가 여러 내부 메서드에서 쓰이지만 단순 필드 참조였기 때문에 
따로 변수로 빼지 않았습니다. 

하지만 roomPrice가 테이블로 분리되면서 이를 참조하려면 쿼리를 보내야 하기 때문에 
변수로 빼서 쿼리 중복을 줄이도록 리팩토링이 필요해 보입니다 

해당 작업 진행하여 커밋하겠습니다 ~

2024-02-06 10:55 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/reservation/service/ReservationService.java
> +            roomQueryUseCase.findRoomPriceByRoom(room).getOffWeekDaysMinFee(), coupon);
작업 완료 
[refactor: roomPrice 쿼리 중복 제거](https://github.com/Upjuyanolja/Upjuyanolja_BE/pull/227/commits/9b620022de4d374ad982fc55dcfa43799ac8809e)

2024-02-06 10:56 UTC, chaewon12 approved these changes
확인 및 수정 완료했습니다 👍

2024-02-06 15:44 UTC, matrixpower1004 approved these changes
브랜치 pull 받아서 확인하였고 현재까지는 에러 없습니다. 수고하셨습니다. 🌹👍

2024-02-07 19:27 UTC, merged