feat : 로그인 / 리프레쉬 토큰 재발급 기능 구현
Upjuyanolja/Upjuyanolja_BE pull request #38
Opened 2023-12-31 03:32 UTC by chadongmin

### 💡Motivation
로그인 / 리프레쉬 토큰 재발급 기능 구현

### 🫱🏻‍🫲🏻To Reviewers
- 새해 복 마~않이 받으세요 😁

2023-12-31 03:34 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/MemberResponse.java
> +
MemberResponseDto는 제가 임의로 만들어놨는데, 의정님께서 작성하신 MemberInfoDto와 똑같은 기능이라 추후 합치도록 할 예정입니다!

2023-12-31 03:38 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/global/security/AuthenticationConfig.java
> +            requestMatchers("/v1/reservations/**").authenticated()
이 부분은 다른 분들의 URI를 보고 추후 수정해야합니다.!

2023-12-31 17:10 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/global/security/SecurityUtil.java
> +            throw new RuntimeException("Security Context에 인증 정보가 없습니다.");
RuntimeException이 아니라 ApplicationException으로 감싸서 던지기로 하지 않았나요?

2023-12-31 17:11 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/global/security/jwt/JwtAuthenticationEntryPoint.java
> +}
EOF 추가해 주시면 좋을 것 같네요.

2024-01-01 08:30 UTC, JeongUijeong requested changes
수고 많으셨습니다! 😊코멘트 몇 가지 남겼으니 확인 후 수정 부탁 드립니다!
추가로, 회원 가입, 로그인, 토큰 재발급 기능에 대한 테스트 코드 꼭 작성 부탁 드립니다~

2024-01-01 08:30 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/RefreshTokenDto.java
> +public class RefreshTokenDto {
DTO 네이밍에 Dto가 들어간 것과 안 들어간 것이 혼재합니다! 컨벤션에 따라 뒤에 Dto를 붙이지 않는 방향으로 수정 부탁드려요~~

2024-01-01 08:30 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
> +        log.info("멤버 아이디 :{}", authentication.getName());
보통 : 를 쓸 때는 앞 문자와 공백 없이, 뒷 내용과는 공백 있게 작성하므로, "멤버 아이디: {}" 형식이 좀 더 적절할 것 같습니다! ㅎㅎ

2024-01-01 08:30 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
> +            .orElseThrow(() -> new RuntimeException("로그아웃 된 사용자입니다."));
예외 처리 시 ApplicationException, 커스텀 익셉션, ErrorCode를 활용해주세요!

2024-01-01 08:30 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/service/MemberAuthService.java
> +            throw new RuntimeException("토큰의 유저 정보가 일치하지 않습니다.");
마찬가지로 ApplicationException, 커스텀 익셉션, ErrorCode를 활용해주세요!

2024-01-01 08:30 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/global/security/jwt/JwtTokenProvider.java
> +        log.info("클레임 정보 : {}", claims.toString());
"클레임 정보: {}" 로 맞춰주시면 어떨까요? ㅎㅎ

2024-01-01 08:30 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/global/security/jwt/JwtTokenProvider.java
> +        return false;
try 문에 return true;와 try-catch 문 종료 후 return false;를 둘 필요 없이 try 시 Exception이 잡히지 않는 경우 true를 반환하도록 하면 되지 않을까요?
```java
        try {
            Jwts.parserBuilder().setSigningKey(key).build().parseClaimsJws(token);
        } catch (io.jsonwebtoken.security.SecurityException | MalformedJwtException e) {
            log.debug("잘못된 JWT 서명 입니다.");
        } catch (ExpiredJwtException e) {
            log.debug("만료된 JWT 토큰 입니다.");
        } catch (UnsupportedJwtException e) {
            log.debug("지원되지 않는 JWT 토큰 입니다.");
        } catch (IllegalArgumentException e) {
            log.debug("JWT 토큰이 잘못 되었습니다.");
        }
        return true;
```

2024-01-04 03:07 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/global/security/SecurityUtil.java
> +            throw new RuntimeException("Security Context에 인증 정보가 없습니다.");
수정했습니다!

2024-01-04 03:07 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/dto/response/RefreshTokenDto.java
> +public class RefreshTokenDto {
수정했습니다!

2024-01-04 03:17 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/global/security/jwt/JwtAuthenticationEntryPoint.java
> +}
EOF를 추가해달라고 하신 말씀은 제가 나중에 더 찾아보고 수정하도록 하겠습니다. 
EOF 빌드 에러 관련하여 구글링 해보니 정확히 어떤 부분으로 발생할 수 있는 에러인지 지금 당장은 잘 모르겠습니다ㅠㅠ

2024-01-04 05:05 UTC, JeongUijeong approved these changes
수고 많으셨습니다~~!!👍🏻👍🏻

2024-01-04 06:06 UTC, decten approved these changes
수고하셨습니다😄

2024-01-04 06:15 UTC, merged