feat : 숙소 전체 페이지 조회 기능 구현
Upjuyanolja/Upjuyanolja_BE pull request #41
Opened 2024-01-04 01:31 UTC by decten

### 💡Motivation
- 코드 공유 목적으로 올렸습니다

### 📌Changes
- 지금 작성하고 있는 풀리퀘스트 양식은 오후 다시 수정하겠습니다

### 🫱🏻‍🫲🏻To Reviewers
- 상세 조회도 다 했는데 끊어서 pr 올렸습니다

2024-01-07 09:27 UTC, JeongUijeong requested changes
정말 수고 많으셨습니다~ ㅎㅎ 기능 구현과 테스트 코드가 함께 PR에 올라와야 해당 기능이 정상적으로 작동하는지 확인이 편합니다! 구현한 기능에 대한 테스트 코드도 함께 올려주시면 감사하겠습니다~😊

2024-01-08 13:35 UTC, decten commented
AccommodationOption인데 계속 ProductOption으로 들어오고 있습니다, 다음 pr 땐 AccommodationOption으로 수정 부탁드립니다😀

2024-01-10 10:58 UTC, decten commented
빌드 에러만 고치고 동작 에러는 해결 못 했습니다 잠시만요

2024-01-10 15:40 UTC, decten commented
[ManyToOne 단방향을 써야 하는 이유](https://velog.io/@kyle/%EB%A7%88%EC%BC%93-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%84%A4%EA%B3%84-1.-%EC%9C%A0%EC%9D%98%EC%A0%90#%EC%A7%80%EC%96%91%ED%95%98%EB%8A%94-%EC%97%B0%EA%B4%80-%EA%B4%80%EA%B3%84)
[언제 양방향을 쓰는 가](https://velog.io/@jhp1115/%EC%96%91%EB%B0%A9%ED%96%A5%EB%B3%B4%EB%8B%A4-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84%EA%B0%80-%EC%A2%8B%EB%8B%A4)

업데이트 쿼리를 많이 사용한다면 양방향을 유지 하는 것이 낫지만, 객실-쿠폰 발급-쿠폰 모두 조회 쿼리를 더 많이 사용하기 때문에 나중에 ManyToOne 단방향으로 변경 하겠습니다

2024-01-10 16:11 UTC, JeongUijeong requested changes
수고 하셨습니다~! 😊 몇 가지 코멘트 달았으니 확인 후 수정 부탁드립니다!

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
> +    private double mapY;
FE에서 X, Y 좌표가 필요 없다고 하셔서 제가 삭제했었습니다! 삭제 부탁드려요~

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
> +    private String shortAddress;
간단 주소라는 명칭 안 쓰기로 하지 않았나요??

2024-01-10 16:11 UTC, JeongUijeong commented on src/test/java/com/backoffice/upjuyanolja/domain/room/unit/repository/RoomRepositoryTest.java
주석 처리 빼주세요~

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
room Entity안에 있기 때문에  굳이 roomPrice라고 할 필요 없을 것 같습니다.. 다시 원래대로 변경 부탁드립니다!

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomStatus roomStatus;
status로 변경 부탁드립니다!

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomOption roomOption;
option으로 수정해주세요~

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private List<RoomImage> roomImages = new ArrayList<>();
images로 수정해주세요~

2024-01-10 16:11 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private List<RoomStock> roomStocks = new ArrayList<>();
stocks로 수정해주세요~

2024-01-10 16:13 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
테이블 명에 맞춰서 roomPrice라고 작성했는데, price라고 짓는 것이 네이밍 규칙에 맞는 건가요??

2024-01-10 16:14 UTC, JeongUijeong requested changes
추가적으로 코멘트 달았습니다~~

2024-01-10 16:14 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Accommodation.java
> +    private AccommodationOption accommodationOption;
option으로 다시 수정 부탁 드립니다!

2024-01-10 16:14 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Accommodation.java
> +    private List<AccommodationImage> accommodationImages = new ArrayList<>();
images로 수정 부탁드립니다!

2024-01-10 16:14 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +public class AccommodationOwnership extends BaseTime {
basetime을 상속 받을 이유가 없는 것 같은데, 혹시 추가하신 이유가 있을까요??

2024-01-10 16:14 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
> +    private String shortAddress;
머지 하면서 옛날꺼랑 섞였나 봅니다,, 수정하겠습니다!

2024-01-10 16:14 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/Address.java
> +    private double mapY;
넵!

2024-01-10 16:15 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
클래스 이름을 보고 알 수 있는 내용을 중복으로 기재할 필요가 없을 것 같습니다~~

2024-01-10 16:16 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
DB 상에서도 테이블 명과 중복된 컬럼 명으로, 불필요하다고 생각합니다!

2024-01-10 16:34 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
테이블에는 roomPrice 컬럼이 저장이 안 되고, 오히려 변수만으로 클래스를 추측할 수 있어야 한다고 생각합니다
https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/
```
Set<BoardSquare> findSquaresToRemove(BoardSquare boardSquare) {...}
```
여기의 BoardSquare가 boardSquare로 변수명을 가지는 것처럼 네이밍 했습니다

2024-01-10 16:40 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +public class AccommodationOwnership extends BaseTime {
대부분의 Entity가 BaseTime을 사용하고 있어서, AccommodationOwnership도 BaseTime을 사용한다고 생각했습니다.
그러면 테이블 마다 BaseTime이 있는 것이 없는 것이 있는 건가요??

2024-01-10 20:51 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
변수로 클래스로 추측할 필요가 있을까요? 클린 코드 강의에서 클래스 내부의 필드는 클래스의 의미를 내포하기 때문에 중복으로 사용할 필요가 없다고 배웠습니다. 현아님이 보여주신 레퍼런스에서도 다음과 같이 나와 있습니다! ㅎㅎ

![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/94631526/c84d8480-720b-4174-bc85-de11bced6d24)

https://dining-developer.tistory.com/68

2024-01-11 02:31 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    private RoomPrice roomPrice;
아하 제가 잘못 읽었네요 수정하겠습니다!
감사합니다😀

2024-01-11 02:31 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +public class AccommodationOwnership extends BaseTime {
@JeongUijeong basetime은 어떻게 할까요??

2024-01-11 04:11 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationService.java
> +        Accommodation accommodation = accommodationRepository.findById(accommodationId).orElseThrow(
이 부분은 JPQL로 orderBy로 정렬해서 최저가의 숙소를 구하면 될 것 같은데, 우선순위 큐를 사용하신 이유가 있으신가요?? 성능 상으로 우선순위큐가 더 빠른가요???

2024-01-11 04:12 UTC, chadongmin approved these changes
고생하셨습니다 현아님!

2024-01-11 04:42 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationService.java
> +        Accommodation accommodation = accommodationRepository.findById(accommodationId).orElseThrow(
숙소에 속하는 room 중에서 저렴한 가격을 찾다 보니 accommo repo에서 orderBy를 안 쓰고 서비스쪽에서 우선 순위 큐를 사용했고, orderBy 정렬 보다는 우선 순위 큐가 더 빠를 거라고 생각했는데 성능 비교를 해보고 오겠습니다
감사합니다!

2024-01-11 04:55 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +public class AccommodationOwnership extends BaseTime {
해당 Entity는 필요 없을 것 같습니다! 삭제해주세요

2024-01-11 05:17 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/service/AccommodationService.java
> +        Accommodation accommodation = accommodationRepository.findById(accommodationId).orElseThrow(
지금 해 본 결과 orderBy를 사용하려면 room 조인이 들어가서 속도가 더 오래 걸리는 걸 확인 했습니다

1. 우선 순위 큐
<img width="250" alt="image" src="https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/52107658/d1a60103-0d2e-4fc6-808a-a67c78d25301">

2. orderBy
<img width="752" alt="image" src="https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/52107658/72d7c38e-d90e-4de9-94be-b8f5fe182a81">
<img width="251" alt="image" src="https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/52107658/f54d7b6b-1bb6-4a1c-863b-1e253b2643b5">

2024-01-11 05:18 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +public class AccommodationOwnership extends BaseTime {
넵!

2024-01-11 05:20 UTC, JeongUijeong requested changes
import 문도 빼주실 수 있나요? 🥹

2024-01-11 05:20 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +import com.backoffice.upjuyanolja.global.common.entity.BaseTime;
ㅠㅠ import 문이 남아 있습니다

2024-01-11 05:21 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/accommodation/entity/AccommodationOwnership.java
> +import com.backoffice.upjuyanolja.global.common.entity.BaseTime;
으악ㅠ 넵 죄송함다ㅠ

2024-01-11 05:23 UTC, JeongUijeong approved these changes
수고하셨습니다! 👍🏻👍🏻👍🏻👍🏻👍🏻

2024-01-11 05:25 UTC, merged