쿠폰, 예약 관련 엔티티 수정
Upjuyanolja/Upjuyanolja_BE pull request #46
Opened 2024-01-04 07:26 UTC by matrixpower1004

### 💡Motivation
PRD에 맞추어 예약과 쿠폰 관련 엔티티 수정

### 📌Changes
- 쿠폰 관련 엔티티 신규 생성 및 수정
- 예약 관련 엔티티 수정
- QueryDSL DI 문제 해결용 configuration 추가

### 🫱🏻‍🫲🏻To Reviewers
QueryDSL 사용 시 Parameter 0 of constructor in xxx 에러를 해결하기 위해 configuration 파일을 추가.

Closes #32 
Closes #33

2024-01-05 12:27 UTC, JeongUijeong requested changes
수고 많으셨습니다~~! 별건 아니지만 몇 가지 소소한 코멘트 남겨드렸습니다~ 반영 가능하시다면 반영 부탁 드리겠습니다! 😊

2024-01-05 12:27 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/Coupon.java
> +    @Comment("구폰 노출 만료일")
오타 수정해주세요~~!
```suggestion
    @Comment("쿠폰 노출 만료일")
```

2024-01-05 12:27 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
> +        "%쿠폰",
별건 아니지만 % 뒤에 한 칸 공백이 있으면 좀 더 보기 편할 것 같습니다 ㅎㅎ
```suggestion
        "% 할인 쿠폰",
        "% 쿠폰",
```

2024-01-05 13:10 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
> +        "%쿠폰",
현재 디자인에서는 공백 없이 붙여서 출력하도록 되어 있습니다. 변경하려면 기획, FE와 협의가 필요한 부분입니다.

2024-01-05 16:43 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
> +        "%쿠폰",
디자인 최종안에 다음과 같이 공백이 있습니다! ㅎㅎ

![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/94631526/2afe33e7-c233-4036-bf09-6873b149323b)
![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/94631526/0d92713a-8938-4a81-bb69-dbe1a5121bf3)
![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/94631526/a0ddc5de-e862-468d-ad10-c70833b0a28c)

2024-01-05 20:08 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/coupon/entity/DiscountType.java
> +        "%쿠폰",
디자인이 그새 또 바뀌었군요. 띄어쓰기 수정되었습니다.

2024-01-08 04:08 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
> +
혹시 RoomStock이 결제 식별자를 가지는 이유가 뭔가요?
객실 재고에 결제 내역이 왜 필요한지 이해가 안가서요

2024-01-08 06:48 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
> +
구두로 설명 들었습니다 🙂
* 코드 제거 필요

2024-01-08 06:51 UTC, chaewon12 commented
예약 관련 엔티티 수정이 필요해서 
제가 해당 브랜치에서 추가 작업 후 PR 업데이트 & 리뷰 재요청 드리겠습니다 !
@JeongUijeong @decten @chadongmin

2024-01-09 02:56 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
>          RoomStatus status,
erd에서는 room이 roomstatus를 가지는데, roomstock로 옮겨진 이유가 궁금합니다

2024-01-09 03:03 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
>          RoomStatus status,
이전 erd 에서는 roomstock에 있었고 
현재 보시는 erd는 pr 이후, 의정님과 회의 에서 변경된 버전입니다!

아직 재고 테이블에 대한 확정안이 나오지 않아 (멘토님께 문의 후 확정) 코드는 변경 전입니다!
재고 테이블이 확정이 된 후 room과 roomstock 코드 수정이 이루어 질 것 같습니다 ~ 
(해당 수정은 의정님이 해주신다고 하셨어요)

2024-01-09 03:08 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/RoomStock.java
>          RoomStatus status,
넵 답변 감사합니다😄
수고 많으셨습니다👍👍

2024-01-09 03:09 UTC, decten approved these changes

2024-01-09 19:37 UTC, JeongUijeong approved these changes
수고하셨습니다! 👍🏻👍🏻

2024-01-10 01:43 UTC, merged