업주 회원가입 기능 구현
Upjuyanolja/Upjuyanolja_BE pull request #56
Opened 2024-01-09 07:45 UTC by chadongmin

### 💡Motivation
- 업주 회원가입 기능을 구현했습니다.

### 📌Changes
- 업주 회원가입의 로직과 시퀀스 다이어그램을 이미지로 첨부합니다!
- Owner라는 엔티티를 추가하였고 가상의 입점 DB 역할을 합니다. 
- Owner 테이블에 존재하는 이메일만 회원가입이 가능하도록 구현하였습니다.
![업주회원가입 플로우 및 시퀀스](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/40655807/3a12f252-9eea-4bb1-9a78-77ab30ee423e)

### 🫱🏻‍🫲🏻To Reviewers
- Approve 부탁드립니다!

2024-01-09 19:47 UTC, JeongUijeong requested changes
수고 많으셨습니다~~😊 
emailConfig에서 필요한 정보가 있는 yaml 파일 공유와 테스트 코드 작성 부탁드립니다!

2024-01-09 19:47 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberEmailDuplicationException.java
>      }
익셉션 클래스 이름은 MemberEmailDuplicationExcpetion인데 에러 코드는 이메일을 찾을 수 없다는 에러코드네요..! 일부러 이렇게 만드신 걸까요??

2024-01-10 00:10 UTC, matrixpower1004 requested changes
수고하셨습니다. 👍

2024-01-10 03:20 UTC, chadongmin commented on src/main/java/com/backoffice/upjuyanolja/domain/member/exception/MemberEmailDuplicationException.java
>      }
로직 개발하다가 제가 실수했네요 ㅎㅎ;; Exception이 너무 많아서...
새로 Exception 만들어서 해당 부분 수정했습니다!!

2024-01-10 16:53 UTC, decten commented
@Import(EmailConfig.class) 이렇게 추가 하셔도 안 되시나요??

2024-01-11 03:59 UTC, decten approved these changes
수고하셨습니다!

2024-01-11 04:29 UTC, chaewon12 approved these changes
고생하셨습니다 🚀

2024-01-11 04:58 UTC, JeongUijeong approved these changes
수고하셨습니다! 😊👍🏻

2024-01-11 05:26 UTC, matrixpower1004 approved these changes
수고하셨습니다. 👍

2024-01-11 05:52 UTC, merged