feat: 포인트 엔터티 초안
Upjuyanolja/Upjuyanolja_BE pull request #63
Opened 2024-01-10 06:00 UTC by decten

### 💡Motivation
- 포인트 엔터티와 레포 초안입니다

### 📌Changes
<img width="443" alt="image" src="https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/52107658/dd13dd8e-1154-4383-9ba0-df7dbba904a3">

### 🫱🏻‍🫲🏻To Reviewers
- erd 설계가 이게 맞는 건지 멘토님께 여쭤보고 수정할 예정입니다
- 지금꺼로 머지 하셔도 되긴 하는데, 멘토님께 확인 받을 예정이라 그 이후에 받으시는 것이 더 나을 것 같습니다

#52

2024-01-10 06:31 UTC, matrixpower1004 requested changes
수고하셨습니다. 리뷰 내용 확인해 주세요. 🌹👍

2024-01-10 06:31 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
> +    @Comment("보유 포인트")
pointType이 ERD에는 유형이라고 나와 있네요. 수정해 주세요.

2024-01-10 06:31 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointRefunds.java
> +    @Comment("포인트 식별자")
comment 수정해 주세요.

2024-01-10 06:31 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointType.java
> +
한 회원이 포인트를 여러번 충전할 수 있는데 회원과 포인트 충전이 관계를 맺는 게 자연스러운 것 아닐까요? 이 부분을 다시 한번 생각해 보면 좋을 것 같습니다.

2024-01-10 06:31 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCharges.java
> +
포인트 결제 이름과 주문 이름은 어떤 차이가 있는거죠?

2024-01-10 06:37 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointCharges.java
> +
어제 설명 드렸듯이 payment가 붙는 건 토스 api 요청 시 식별용이고, order는 영수증에 사용하는 용도입니다
토스 api 사용할 때 payment와 order 필드 모두 필요해서 2개가 따로 존재합니다

2024-01-10 06:39 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointType.java
> +
erd를 포인트-사용자가 아닌 포인트 충전-사용자로 변경하자는 말씀이실까요?

2024-01-10 06:44 UTC, matrixpower1004 commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointType.java
> +
포인트와 회원 중간에 포인트 충전 테이블이 있어야 할 것 같네요. 비즈니스 로직으로도 회원이 충전을 해야 포인트가 생기는 거니까요.

2024-01-10 06:54 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointType.java
> +
포인트에서 포인트 충전이 아니고 포인트 충전이 포인트를 가지는 건가요?

2024-01-10 06:54 UTC, decten commented
point_usage가 포인트 사용입니다

2024-01-10 16:07 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
> +    @OneToMany(mappedBy = "point", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
포인트를 가져올 때 포인트 충전/사용/환불을 같이 가져오고, 포인트 충전/사용/환불에서 해당하는 포인트를 가져와야 하기 때문에 양방향이라 생각했는데, 여기도 단방향으로 바꿔야 한다면 말씀 부탁드립니다

2024-01-11 02:52 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/PointType.java
> +
dbeaver erd가 이상하게 만들어진 문제였음

2024-01-11 02:53 UTC, matrixpower1004 approved these changes
수고하셨습니다. 👍🌹✔

2024-01-11 04:38 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
> +
Point는 상태값을 따로 안가져도 괜찮은가요?
환불 여부 체크 같은 경우에 쓰이지 않나 해서요! 
PointRefunds 에서 조회하는 흐름일까요

2024-01-11 05:26 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
> +
PointType에서 사용/충전으로 나누고, 포인트 충전에서 환불 체크 필드를 따로 뒀습니다😀

2024-01-11 05:28 UTC, matrixpower1004 approved these changes
수고하셨습니다. 👍

2024-01-11 08:58 UTC, decten commented on src/main/java/com/backoffice/upjuyanolja/domain/point/entity/Point.java
> +
@chaewon12 채원님 혹시 답변 확인 하시고 승인 해주실 수 있을까요??

2024-01-11 09:02 UTC, chaewon12 approved these changes
고생하셨습니다~

2024-01-11 09:03 UTC, merged