feat: 객실 수정 기능 구현
Upjuyanolja/Upjuyanolja_BE pull request #81
Opened 2024-01-13 11:46 UTC by JeongUijeong

### 💡Motivation
- 업주 회원이 보유한 숙소의 객실을 수정할 수 있도록 객실 수정 기능을 구현해야 합니다. 

### 📌Changes
- 객실 수정 기능 구현
- 객실 수정 기능 테스트 작성
- 객실 수정 API Docs 테스트 + adoc 작성

### 🫱🏻‍🫲🏻To Reviewers
- 코드 리뷰와 승인 부탁 드립니다~!

closes #79

2024-01-13 14:15 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    }
가장 core 라고 할 수 있는 Entity가 외부 요청 DTO를 의존하고 있는 구조로 보여지는데
이는 요구사항의 변경(즉, DTO)이 생긴다면 그 변경이 Entity 까지 전파된다는 문제가 생길 것 같습니다. 
저는 Entity가 DTO를 아는 것이 아닌  DTO가 Entity를 아는 꼴이 되어야 한다고 생각해요 

또, updateRoom() 은 RoomUpdateRequest만을 받아야 하기 때문에 
시스템이 확장되어 updateRoom() 을 여러곳에서 사용하고 싶어도 사용할수도 없을 것 같습니다. 재사용성이 떨어진다는 것이죠...!

넘겨야 할 파라미터가 많아서 Request DTO를 바로  보내신 것이라면 
controller-service 사이에 DTO를 두신 것처럼 service-domain 사이에도 dto를 하나 두는 것으로 개선할 수 있을것 같습니다
`RoomUpdateRequest` -> `RoomUpdateDTO` -> `Room`

2024-01-13 14:19 UTC, chaewon12 requested changes
주말인데 고생하셨습니다 ~ 👍 
Entity와 RequestDTO의 의존 관계에 대해 제 생각을 리뷰로 남겨두었으니 고려해주세요

2024-01-13 14:44 UTC, matrixpower1004 approved these changes
수고하셨습니다. Entity에서 dto를 주입 받아 업데이트를 하는 로직은 변경을 고려해 보면 좋을 것 같습니다. 현재의 로직은 dto가 변경되면 entity 까지도 영향이 전파되는 구조인데, 꼭 필요한 필드만 엔티티에서 setter를 설정하거나 다른 의미있는 메서드를 만들어서 사용하는 게 좋을 것 같습니다.

2024-01-13 19:00 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +    }
네! 채원님 피드백 감사합니다~~! 중간 DTO 생성하여 외부 변경으로 Entity까지 영향이 미치지 않도록 하겠습니다!! 😊👍🏻

2024-01-14 05:10 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +import com.backoffice.upjuyanolja.domain.room.exception.InvalidRoomStatusException;
사용하지 않는 import문 제거 해주세요

2024-01-14 05:10 UTC, chaewon12 commented on src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
> +        }
RoomUpdateRequest 와 Entity 사이의 의존을 끊기 위해 사이에 dto를 두기로 한건데 
그 dto(RoomUpdate)가 RoomUpdateRequest를 의존한다면 결국 RoomUpdateRequest 와 Entity 사이의 의존은 끊어지지 않는 구조인 것 같습니다... 

마찬가지로 RoomUpdate의 입장에서는 RoomUpdate가 RoomUpdateRequest를 아는 구조가 아닌 RoomUpdateRequest가 RoomUpdate를 아는 구조여야 한다는 거죠

2024-01-14 05:12 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/service/usecase/RoomCommandUseCase.java
> +        }
에고고 오늘 저녁에 다시 수정해서 올릴게요~!!

2024-01-14 05:12 UTC, JeongUijeong commented on src/main/java/com/backoffice/upjuyanolja/domain/room/entity/Room.java
> +import com.backoffice.upjuyanolja.domain.room.exception.InvalidRoomStatusException;
네~ 꼼꼼한 리뷰 감사합니다!!☺️

2024-01-15 01:15 UTC, chaewon12 approved these changes

2024-01-15 01:20 UTC, merged